### ISSUE TITLE
Update for Dark Fog Facilities

### ISSUE THREAD

**Issue by HorstdasPferd** [Shad0wlife/DSP_AssemblerUI#11]
Hi, a lot of new Buildings and Items were introduced and may need some verification. 
When using only this mod i got this error once i click a building (test with both, assembler and smelter)
![image](https://github.com/Shad0wlife/DSP_AssemblerUI/assets/154055707/5c4a9a9b-bf32-4a95-aa5a-7eccbab485f4)

Do you need the new recipes/buildings (there are mk3 Assembler and smelters and a new lab type (best found in sandbox mode, build menue 8) as a .csv or screenshots?

**Comment by Shad0wlife** [comment]
Thanks for the additional information. I guess they reworked the UI system somewhat, I gotta check how it's done now to put stuff in the right place

**Comment by Shad0wlife** [comment]
Ok, the issue in itself is just that the mod was compiled against an old version of the game. Recompiling fixed the error you have.

I'll check different crafting buildings next, to make sure that they all work (if they use the "default" UI).

Buildings with new UI will come later (like the advanced miner which is still not done for example)

**Comment by Shad0wlife** [comment]
The production buildings (assembler, smelter) work fine. The support for dark fog comes with the build of v2.3.0 on the Releases page.

This mod never supported research buildings, I'll have to see if it makes sense to add that and if I can find the time for it.

**Comment by HorstdasPferd** [comment]
For labs it might be difficult because of so many different positions and demands in the UI. as well as the research wich  dont even "produces" something. 

Anyway, thanks m8!
