### ISSUE TITLE
Bug: Missing calculation for 4th Input item in an assembler

### ISSUE THREAD

**Issue by achyutde13** [Shad0wlife/DSP_AssemblerUI#4]
The 4th and 5th item required for a recipe doesn't have the input speed calculation displayed. I have attached a pic.
![Dyson Sphere Program Screenshot 2021 08 02 - 05 54 46 93](https://user-images.githubusercontent.com/38592400/127790293-5ff7f85e-e29b-4c5d-9412-ad03ae526a04.jpg)

**Comment by Shad0wlife** [comment]
Huh, I was not aware there were recipes with more than 3 inputs. Thanks, will correct that. And maybe also fix the slight offset when using per second mode.

**Comment by achyutde13** [comment]
There's even with 5 inputs! (Ray receivers). Thanks! Love your mod!

**Comment by Shad0wlife** [comment]
Should be fixed in v2.1.0, added compatibility for up to 5 item fields.
