### ISSUE TITLE
Shows all Assembler rates as 0/min as of latest update

### ISSUE THREAD

**Issue by Detailer88** [Shad0wlife/DSP_AssemblerUI#7]
Miners function correctly. Tried clearing config and reinstalling nothing worked.

**Comment by Detailer88** [comment]
Here is the message from the error log:

[Info   :   BepInEx] Loading [Assembler UI Speed Info Mod 2.1.0.0]
[Error  :AssemblerSpeedUIMod] [UIAssemblerWindow] Could not find the desired fields for patching the update logic.

**Comment by Shad0wlife** [comment]
Thank you for the report. I'm going to check it out right now!

**Comment by Shad0wlife** [comment]
Closed with latest Update (Version 2.2.1).
