### ISSUE TITLE
Show more decimal places.

### ISSUE THREAD

**Issue by daniele-bondi** [Shad0wlife/DSP_AssemblerUI#9]
For example, if a recipe consumes 2 items every 3 seconds, I would like to be able to see a consumption of "0.66/s".

**Comment by Bloxxxi** [comment]
Bump!
I really wish to see more decimal places as well. It would make the game so much more enjoyable imo.

**Comment by Shad0wlife** [comment]
Sounds like a good idea. I haven't worked on this in a while, so I'll have to see how more decimal places would affect the label placement and such, but apart from that this should be somewhat simple to add.

**Comment by Bloxxxi** [comment]
Thank you for responding! No pressure obviously tho since you already did god's work with this mod.

**Comment by Shad0wlife** [comment]
This was quite hard to do with the dynamic label placement, but now the labels should adapt to their available space (this may lead to different font sizes for different input, if the number of characters shown differs too much - I'm too lazy to make sure they are all the same, and in most cases it is unnoticable).

Version 2.3.0 added the feature and the release was built against dark fog, so should work with that game update.

**Comment by Bloxxxi** [comment]
Absolute Gigachad right here. Thank you a lot @Shad0wlife
